USE [AuctionCommerce];
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [dbo].[User_UserRole_Mapping]([User_Id], [UserRole_Id])
SELECT 1, 1 UNION ALL
SELECT 2, 1 UNION ALL
SELECT 3, 1 UNION ALL
SELECT 4, 1 UNION ALL
SELECT 5, 1 UNION ALL
SELECT 6, 1 UNION ALL
SELECT 7, 1 UNION ALL
SELECT 8, 1 UNION ALL
SELECT 9, 1
COMMIT;
RAISERROR (N'[dbo].[User_UserRole_Mapping]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

