USE [AuctionCommerce];
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [dbo].[User_UserRole_Mapping]([User_Id], [UserRole_Id])
SELECT 11, 1 UNION ALL
SELECT 12, 1 UNION ALL
SELECT 13, 1 UNION ALL
SELECT 14, 1 UNION ALL
SELECT 15, 1 UNION ALL
SELECT 16, 1 UNION ALL
SELECT 17, 1 UNION ALL
SELECT 18, 1 UNION ALL
SELECT 19, 1 UNION ALL
SELECT 20, 1 UNION ALL
SELECT 1, 2
COMMIT;
RAISERROR (N'[dbo].[User_UserRole_Mapping]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

